import "./globals.css";

import { Inter } from "next/font/google";
import { ThemeProvider } from "./lib/context/theme";
import AppBar from "./components/AppBar";
import { AppBarProvider } from "./components/AppBar/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppBarProvider>
            <AppBar />
            {children}
          </AppBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
