import "./globals.css";

import { Inter } from "next/font/google";
import { ThemeProvider } from "./lib/context/theme";
import AppBar from "./lib/components/app-bar";
import { AppBarProvider } from "./lib/components/app-bar/context";
import { QueryProvider } from "./lib/context/query";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <QueryProvider>
            <AppBarProvider>
              <AppBar />
              {children}
            </AppBarProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
